using MoqaLate.Autogenerated;

namespace InAppPurchaseToggle.Tests.ConcreteTestToggles
{
    public class MultiFeatureWithNonDefualtFormatter : RepeatPurchaseToggleBase
    {
        protected override int SetNumberOfRepeats()
        {
            return 1;
        }

        protected override IRepeatPurchaseToggleNameInstanceFormatter SetNameInstanceFormatter()
        {
            return new RepeatPurchaseToggleNameInstanceFormatterMoqaLate();
        }
    }
}