using MoqaLate.Autogenerated;

namespace InAppPurchaseToggle.Tests.ConcreteTestToggles
{
    public class MultiFeatureWithNonDefualtFormatter : RepeatToggleBase
    {
        protected override int SetNumberOfRepeats()
        {
            return 1;
        }

        protected override IRepeatToggleInstanceNumberConcatinator SetInstanceNumberFormatter()
        {
            return new RepeatToggleInstanceNumberConcatinatorMoqaLate();
        }
    }
}