using MoqaLate.Autogenerated;

namespace InAppPurchaseToggle.Tests.ConcreteTestToggles
{
    public class RepeatPurchaseWithNonDefualtFormatter : RepeatPurchaseToggleBase
    {
        protected override int SetAvailableStoreInstances()
        {
            return 1;
        }

        protected override IRepeatPurchaseToggleNameInstanceFormatter SetNameInstanceFormatter()
        {
            return new RepeatPurchaseToggleNameInstanceFormatterMoqaLate();
        }
    }
}