using InAppPurchaseToggle;
namespace MoqaLate.Autogenerated
{
public partial class RepeatPurchaseToggleNameInstanceFormatterMoqaLate : IRepeatPurchaseToggleNameInstanceFormatter
{


// -------------- Format ------------ 

private string _formatReturnValue;

        private int _formatNumberOfTimesCalled;

        public string FormatParameter_toggleName_LastCalledWith;public int FormatParameter_instanceNumber_LastCalledWith;
        
        public virtual void FormatSetReturnValue(string value)
        {
            _formatReturnValue = value;
        }    


        public virtual bool FormatWasCalled()
{
   return _formatNumberOfTimesCalled > 0;
}


public virtual bool FormatWasCalled(int times)
{
   return _formatNumberOfTimesCalled == times;
}


public virtual int FormatTimesCalled()
{
   return _formatNumberOfTimesCalled;
}


public virtual bool FormatWasCalledWith(string toggleName, int instanceNumber){
return (
toggleName.Equals(FormatParameter_toggleName_LastCalledWith)  && 
instanceNumber.Equals(FormatParameter_instanceNumber_LastCalledWith) );
}
 

             public string Format(string toggleName, int instanceNumber)
        {
            _formatNumberOfTimesCalled++;            

            FormatParameter_toggleName_LastCalledWith = toggleName;FormatParameter_instanceNumber_LastCalledWith = instanceNumber;

            return _formatReturnValue;
        }}
}
