using InAppPurchaseToggle;
namespace MoqaLate.Autogenerated
{
public partial class RepeatPurchaseToggleNameInstanceFormatterMoqaLate : IRepeatPurchaseToggleNameInstanceFormatter
{


// -------------- Format ------------ 

private string _formatReturnValue;

        private int _formatNumberOfTimesCalled;

        public string FormatParameter_storeInAppOfferBaseName_LastCalledWith;public int FormatParameter_repeatInstanceNumber_LastCalledWith;
        
        public virtual void FormatSetReturnValue(string value)
        {
            _formatReturnValue = value;
        }    


        public virtual bool FormatWasCalled()
{
   return _formatNumberOfTimesCalled > 0;
}


public virtual bool FormatWasCalled(int times)
{
   return _formatNumberOfTimesCalled == times;
}


public virtual int FormatTimesCalled()
{
   return _formatNumberOfTimesCalled;
}


public virtual bool FormatWasCalledWith(string storeInAppOfferBaseName, int repeatInstanceNumber){
return (
storeInAppOfferBaseName.Equals(FormatParameter_storeInAppOfferBaseName_LastCalledWith)  && 
repeatInstanceNumber.Equals(FormatParameter_repeatInstanceNumber_LastCalledWith) );
}
 

             public string Format(string storeInAppOfferBaseName, int repeatInstanceNumber)
        {
            _formatNumberOfTimesCalled++;            

            FormatParameter_storeInAppOfferBaseName_LastCalledWith = storeInAppOfferBaseName;FormatParameter_repeatInstanceNumber_LastCalledWith = repeatInstanceNumber;

            return _formatReturnValue;
        }}
}
