using InAppPurchaseToggle;
namespace MoqaLate.Autogenerated
{
public partial class RepeatPurchaseToggleNameInstanceFormatterMoqaLate : IRepeatPurchaseToggleNameInstanceFormatter
{


// -------------- Combine ------------ 

private string _combineReturnValue;

        private int _combineNumberOfTimesCalled;

        public string CombineParameter_toggleName_LastCalledWith;public int CombineParameter_instanceNumber_LastCalledWith;
        
        public virtual void CombineSetReturnValue(string value)
        {
            _combineReturnValue = value;
        }    


        public virtual bool CombineWasCalled()
{
   return _combineNumberOfTimesCalled > 0;
}


public virtual bool CombineWasCalled(int times)
{
   return _combineNumberOfTimesCalled == times;
}


public virtual int CombineTimesCalled()
{
   return _combineNumberOfTimesCalled;
}


public virtual bool CombineWasCalledWith(string toggleName, int instanceNumber){
return (
toggleName.Equals(CombineParameter_toggleName_LastCalledWith)  && 
instanceNumber.Equals(CombineParameter_instanceNumber_LastCalledWith) );
}
 

             public string Format(string toggleName, int instanceNumber)
        {
            _combineNumberOfTimesCalled++;            

            CombineParameter_toggleName_LastCalledWith = toggleName;CombineParameter_instanceNumber_LastCalledWith = instanceNumber;

            return _combineReturnValue;
        }}
}
