using System;
using InAppPurchaseToggle;
namespace MoqaLate.Autogenerated
{
public partial class SingleToggleToStoreInAppOfferNameMapperMoqaLate : ISingleToggleToStoreInAppOfferNameMapper
{


// -------------- Map ------------ 

private string _mapReturnValue;

        private int _mapNumberOfTimesCalled;

        public Type MapParameter_concreteToggleType_LastCalledWith;
        
        public virtual void MapSetReturnValue(string value)
        {
            _mapReturnValue = value;
        }    


        public virtual bool MapWasCalled()
{
   return _mapNumberOfTimesCalled > 0;
}


public virtual bool MapWasCalled(int times)
{
   return _mapNumberOfTimesCalled == times;
}


public virtual int MapTimesCalled()
{
   return _mapNumberOfTimesCalled;
}


public virtual bool MapWasCalledWith(Type concreteToggleType){
return (
concreteToggleType.Equals(MapParameter_concreteToggleType_LastCalledWith) );
}
 

             public string Map(Type concreteToggleType)
        {
            _mapNumberOfTimesCalled++;            

            MapParameter_concreteToggleType_LastCalledWith = concreteToggleType;

            return _mapReturnValue;
        }}
}
