using InAppPurchaseToggle;
namespace MoqaLate.Autogenerated
{
public partial class WindowsStoreGatewayMoqaLate : IWindowsStoreGateway
{


// -------------- LookupActiveStatus ------------ 

private bool _lookupActiveStatusReturnValue;

        private int _lookupActiveStatusNumberOfTimesCalled;

        public string LookupActiveStatusParameter_inAppOfferName_LastCalledWith;
        
        public virtual void LookupActiveStatusSetReturnValue(bool value)
        {
            _lookupActiveStatusReturnValue = value;
        }    


        public virtual bool LookupActiveStatusWasCalled()
{
   return _lookupActiveStatusNumberOfTimesCalled > 0;
}


public virtual bool LookupActiveStatusWasCalled(int times)
{
   return _lookupActiveStatusNumberOfTimesCalled == times;
}


public virtual int LookupActiveStatusTimesCalled()
{
   return _lookupActiveStatusNumberOfTimesCalled;
}


public virtual bool LookupActiveStatusWasCalledWith(string inAppOfferName){
return (
inAppOfferName.Equals(LookupActiveStatusParameter_inAppOfferName_LastCalledWith) );
}
 

             public bool LookupActiveStatus(string inAppOfferName)
        {
            _lookupActiveStatusNumberOfTimesCalled++;            

            LookupActiveStatusParameter_inAppOfferName_LastCalledWith = inAppOfferName;

            return _lookupActiveStatusReturnValue;
        }}
}
