using System;
using InAppPurchaseToggle.Tests.HandCodedMocks;
using InAppPurchaseToggle.Tests.TestFeatures;
using MoqaLate.Autogenerated;
using Xunit;

namespace InAppPurchaseToggle.Tests
{
    public class ConcreteRepeatToggleTests
    {
        [Fact]
        public void ShouldDefaultToRealWindowsStoreGateway()
        {
            var sut = new MultiFeatureWith123Instances();

            Assert.IsType(typeof (RealWindowsStoreGateway), sut.WindowsStoreGateway);
        }


        [Fact]
        public void ShouldDefaultToUnderscoreIntanceNumberFormatter()
        {
            var sut = new MultiFeatureWith123Instances();

            Assert.IsType(typeof(NameUnderscoreNumberFormatter), sut.ToggleInstanceNumberFormatter);
        }

        [Fact]
        public void ShouldReturnTotalRepeatOffersAvailable()
        {
            var sut = new MultiFeatureWith123Instances();

            var totalOffers = sut.TotalRepeatsAvailable;
            
            Assert.Equal(123, totalOffers);
        }


        [Fact]
        public void ShouldErrorIfDerivedToggleWithZeroRepeats()
        {
            var sut = new MultiFeatureWithZeroRepeats();

            Assert.Throws<InvalidOperationException>(() => { var totalOffers = sut.TotalRepeatsAvailable; });            
        }


        [Fact]
        public void ShouldErrorIfDerivedToggleWithNegativeRepeats()
        {
            var sut = new MultiFeatureWithNegativeRepeats();

            Assert.Throws<InvalidOperationException>(() => { var totalOffers = sut.TotalRepeatsAvailable; });
        }






         [Fact]
        public void ShouldCallGatewayAsManyTimesAsThereAreOfferNumbersWhenCalculatingTotalPurchased()
        {
            var mockGateway = new WindowsStoreGatewayMoqaLate();
            mockGateway.IsPurchasedSetReturnValue(true);

            var sut = new MultiFeatureWith123Instances()
                          {
                              WindowsStoreGateway = mockGateway
                          };

            var total = sut.GetTotalPurchased();

            Assert.Equal(123, mockGateway.IsPurchasedTimesCalled());
        }


         [Fact]
         public void ShouldCallNameFormatterAsManyTimesAsThereAreOfferNumbersWhenCalculatingTotalPurchased()
         {
             var mockGateway = new WindowsStoreGatewayMoqaLate();
             mockGateway.IsPurchasedSetReturnValue(true);

             var mockConcat = new  RepeatToggleInstanceNumberConcatinatorMoqaLate();

             var sut = new MultiFeatureWith123Instances()
             {
                 WindowsStoreGateway = mockGateway,
                 ToggleInstanceNumberFormatter = mockConcat
             };

             var total = sut.GetTotalPurchased();

             Assert.Equal(123, mockConcat.CombineTimesCalled());
         }




         [Fact]
         public void ShouldReturnIfSpecificInstanceHasBeenPurchased()
         {
             var mockGateway = new WindowsStoreGatewayMoqaLate();
             mockGateway.IsPurchasedSetReturnValue(true);

             var sut = new MultiFeatureWith123Instances()
             {
                 WindowsStoreGateway = mockGateway
             };

             var isPurchased = sut.IsInstancePurchased(123);

             Assert.True(isPurchased);

             // TODO: this should prob be in sep test
             // Due to current limitations with MoqaLate, we can only get what the last call was for a particular method
             mockGateway.IsPurchasedWasCalledWith("MultiFeatureWith123Instances_123");


             // test the negative version
             mockGateway.IsPurchasedSetReturnValue(false);
             
             isPurchased = sut.IsInstancePurchased(123);

             Assert.False(isPurchased);

             // TODO: this should prob be in sep test
             // Due to current limitations with MoqaLate, we can only get what the last call was for a particular method
             mockGateway.IsPurchasedWasCalledWith("MultiFeatureWith123Instances_123");
         }


         [Fact]
         public void ShouldCalculateIfAllInstancesHaveNotBeenPurchased()
         {
             var mockGateway = new WindowsStoreGatewayHandMock
                                   {
                                       DefaultIsPurchasedValue = true,
                                       OddOneOitInAppOfferNameToReturnNotDefaultValue =
                                           "MultiFeatureWith123Instances_99"
                                   };

             var sut = new MultiFeatureWith123Instances()
             {
                 WindowsStoreGateway = mockGateway
             };

             var allPurchased = sut.IsAllPurchased();

             Assert.False(allPurchased);
         }


         [Fact]
         public void ShouldCalculateIfAllInstancesHaveBeenPurchased()
         {
             var mockGateway = new WindowsStoreGatewayMoqaLate();
             mockGateway.IsPurchasedSetReturnValue(true);

             var sut = new MultiFeatureWith123Instances()
             {
                 WindowsStoreGateway = mockGateway
             };

             var allPurchased = sut.IsAllPurchased();

             Assert.True(allPurchased);
         }

        // test defualt combiner

        //[Fact]
        //public void ShouldMapName()
        //{
        //    var mockNameMapper = new ToggleToInAppOfferNameMapperMoqaLate();

        //    var sut = new Feature1
        //                  {
        //                      WindowsStoreGateway = new WindowsStoreGatewayMoqaLate(),
        //                      InAppOfferNameMapper = mockNameMapper
        //                  };

        //    var dontCare = sut.IsPurchased;

        //    Assert.True(mockNameMapper.MapWasCalledWith(sut));
        //}
    }
}