using InAppPurchaseToggle.PortableCoreTests.TestFeatures;
using InAppPurchaseToggle.WindowsStore;
using MoqaLate.Autogenerated;
using Xunit;

namespace InAppPurchaseToggle.Tests
{
    public class ConcreteToggleTests
    {
        [Fact]
        public void ShouldDefaultToRealWindowsStoreGateway()
        {
            var sut = new Feature1();

            Assert.IsType(typeof (RealWindowsStoreGateway), sut.WindowsStoreGateway);
        }


        [Fact]
        public void ShouldCallConfiguredGateway()
        {
            var sut = new Feature1();

            var mockGateway = new WindowsStoreGatewayMoqaLate();
            mockGateway.LookupActiveStatusSetReturnValue(true);

            sut.WindowsStoreGateway = mockGateway;

            var result = sut.IsPurchased;

            Assert.True(mockGateway.LookupActiveStatusWasCalledWith("Feature1"));
            Assert.True(result);
        }

        [Fact]
        public void ShouldMapName()
        {
            var sut = new Feature1();

            var mockGateway = new WindowsStoreGatewayMoqaLate();
            var mockNameMapper = new ToggleToInAppOfferNameMapperMoqaLate();

            sut.WindowsStoreGateway = mockGateway;
            sut.InAppOfferNameMapper = mockNameMapper;

            var result = sut.IsPurchased;

            Assert.True(mockNameMapper.MapWasCalledWith(sut));
        }
    }
}