using InAppPurchaseToggle.PortableCoreTests.TestFeatures;
using InAppPurchaseToggle.WindowsStore;
using MoqaLate.Autogenerated;
using Xunit;

namespace InAppPurchaseToggle.Tests
{
    public class ConcreteToggleTests
    {
        [Fact]
        public void ShouldDefaultToRealWindowsStoreGateway()
        {
            var sut = new Feature1();
            
            Assert.IsType(typeof(RealWindowsStoreGateway), sut.WindowsStoreGateway);
        }


        [Fact]
        public void ShouldCallConfiguredGateway()
        {
            var sut = new Feature1();

            var mockg = new WindowsStoreGatewayMoqaLate();
            mockg.LookupActiveStatusSetReturnValue(true);
          
            sut.WindowsStoreGateway = mockg;

            var result = sut.IsPurchased;

            Assert.True(mockg.LookupActiveStatusWasCalledWith("Feature1"));
            Assert.True(result);
        }

     //   [Fact]
        //public void ShouldCallConfiguredGateway()
        //{
        //    var sut = new Feature1();

        //    var mockg = new Mock<IWindowsStoreGateway>();
        //    mockg.Setup(x => x.LookupActiveStatus("Feature1")).Returns(true);

        //    sut.WindowsStoreGateway = mockg.Object;

        //    var result = sut.IsPurchased;

        //    mockg.Verify(x => x.LookupActiveStatus("Feature1"),Times.Once());
        //    Assert.True(result);
        //}
   }
}
