using InAppPurchaseToggle.Tests.TestFeatures;
using MoqaLate.Autogenerated;
using Xunit;

namespace InAppPurchaseToggle.Tests
{
    public class ConcreteToggleTests
    {
        [Fact]
        public void ShouldDefaultToRealWindowsStoreGateway()
        {
            var sut = new Feature1();

            Assert.IsType(typeof (RealWindowsStoreGateway), sut.WindowsStoreGateway);
        }


        [Fact]
        public void ShouldUseSpecifiedWindowsStoreGateway()
        {
            var mockGateway = new WindowsStoreGatewayMoqaLate();
            mockGateway.IsPurchasedSetReturnValue(true);

            var sut = new Feature1
                          {
                              WindowsStoreGateway = mockGateway
                          };

            var result = sut.IsPurchased;

            Assert.True(mockGateway.IsPurchasedWasCalledWith("Feature1"));
            Assert.True(result);
        }


        [Fact]
        public void ShouldMapName()
        {
            var mockNameMapper = new ToggleToInAppOfferNameMapperMoqaLate();

            var sut = new Feature1
                          {
                              WindowsStoreGateway = new WindowsStoreGatewayMoqaLate(),
                              InAppOfferNameMapper = mockNameMapper
                          };

            var dontCare = sut.IsPurchased;

            Assert.True(mockNameMapper.MapWasCalledWith(sut.GetType()));
        }
    }
}