using System;
using InAppPurchaseToggle.Tests.ConcreteTestToggles;
using InAppPurchaseToggle.Tests.HandCodedMocks;
using MoqaLate.Autogenerated;
using Xunit;

namespace InAppPurchaseToggle.Tests
{
    public class RepeatToggleTests
    {
        [Fact]
        public void ShouldDefaultToRealWindowsStoreGateway()
        {
            var sut = new RepeatPurchaseWith123Instances();

            Assert.IsType(typeof (RealStoreGateway), sut.StoreGateway);
        }


        [Fact]
        public void ShouldDefaultToUnderscoreIntanceNumberFormatter()
        {
            var sut = new RepeatPurchaseWith123Instances();

            Assert.IsType(typeof(NameUnderscoreNumberFormatter), sut.NameInstanceFormatter);
        }

        [Fact]
        public void ShouldReturnTotalOffersAvailable()
        {
            var sut = new RepeatPurchaseWith123Instances();

            var totalOffers = sut.AvailableStoreInstances;
            
            Assert.Equal(123, totalOffers);
        }


        [Fact]
        public void ShouldErrorIfToggleSetsZeroInstances()
        {
            Assert.Throws<InvalidOperationException>(() => { new RepeatPurchaseWithZeroInstances(); });
        }


        [Fact]
        public void ShouldErrorIfDerivedToggleWithNegativeInstances()
        {
            Assert.Throws<InvalidOperationException>(() => { new RepeatPurchaseWithNegativeInstances(); });
        }
        

        [Fact]
        public void ShouldCallGatewayAsManyTimesAsThereAreOfferNumbersWhenCalculatingTotalPurchased()
        {
            var mockGateway = new StoreGatewayMoqaLate();
            mockGateway.IsPurchasedSetReturnValue(true);

            var sut = new RepeatPurchaseWith123Instances()
                          {
                              StoreGateway = mockGateway
                          };

            sut.GetTotalPurchased();

            Assert.Equal(123, mockGateway.IsPurchasedTimesCalled());
        }


         [Fact]
         public void ShouldCallNameFormatterAsManyTimesAsThereAreOfferNumbersWhenCalculatingTotalPurchased()
         {
             var mockGateway = new StoreGatewayMoqaLate();
             mockGateway.IsPurchasedSetReturnValue(true);

             var mockConcat = new  RepeatPurchaseToggleNameInstanceFormatterMoqaLate();

             var sut = new RepeatPurchaseWith123Instances()
             {
                 StoreGateway = mockGateway,
                 NameInstanceFormatter = mockConcat
             };

             sut.GetTotalPurchased();

             Assert.Equal(123, mockConcat.FormatTimesCalled());
         }
        

         [Fact]
         public void ShouldReturnIfSpecificInstanceHasBeenPurchased()
         {
             var mockGateway = new StoreGatewayMoqaLate();
             mockGateway.IsPurchasedSetReturnValue(true);

             var sut = new RepeatPurchaseWith123Instances()
             {
                 StoreGateway = mockGateway
             };

             var isPurchased = sut.IsInstancePurchased(123);

             Assert.True(isPurchased);

             // TODO: this should prob be in sep test
             // Due to current limitations with MoqaLate, we can only get what the last call was for a particular method
             mockGateway.IsPurchasedWasCalledWith("MultiFeatureWith123Instances_123");


             // test the negative version
             mockGateway.IsPurchasedSetReturnValue(false);
             
             isPurchased = sut.IsInstancePurchased(123);

             Assert.False(isPurchased);

             // TODO: this should prob be in sep test
             // Due to current limitations with MoqaLate, we can only get what the last call was for a particular method
             mockGateway.IsPurchasedWasCalledWith("RepeatPurchaseWith123Instances_123");
         }


         [Fact]
         public void ShouldCalculateIfAllInstancesHaveNotBeenPurchased()
         {
             var mockGateway = new StoreGatewayHandMock
                                   {
                                       DefaultIsPurchasedValue = true,
                                       OddOneOutInAppOfferNameToReturnNotDefaultValue =
                                           "RepeatPurchaseWith123Instances_99"
                                   };

             var sut = new RepeatPurchaseWith123Instances()
             {
                 StoreGateway = mockGateway
             };

             var allPurchased = sut.IsAllPurchased();

             Assert.False(allPurchased);
         }


         [Fact]
         public void ShouldCalculateIfAllInstancesHaveBeenPurchased()
         {
             var mockGateway = new StoreGatewayMoqaLate();
             mockGateway.IsPurchasedSetReturnValue(true);

             var sut = new RepeatPurchaseWith123Instances()
             {
                 StoreGateway = mockGateway
             };

             var allPurchased = sut.IsAllPurchased();

             Assert.True(allPurchased);
         }
        

         [Fact]
         public void ShouldCalculateNextLowestUnPurchased()
         {
             var mockGateway = new StoreGatewayHandMock
             {
                 DefaultIsPurchasedValue = true,
                 OddOneOutInAppOfferNameToReturnNotDefaultValue =
                     "RepeatPurchaseWith123Instances_99"
             };

             var sut = new RepeatPurchaseWith123Instances()
             {
                 StoreGateway = mockGateway
             };

             var nextUnpurchasedInstance = sut.GetNextLowestUnpurchasedInstance();

             Assert.Equal(99, nextUnpurchasedInstance);
         }


         [Fact]
         public void ShouldGracefullyHandleNextLowestUnPurchasedWhenAllHaveBeenPurchased()
         {
             var mockGateway = new StoreGatewayMoqaLate();
             mockGateway.IsPurchasedSetReturnValue(true);

             var sut = new RepeatPurchaseWith123Instances()
             {
                 StoreGateway = mockGateway
             };

             var nextUnpurchasedInstance = sut.GetNextLowestUnpurchasedInstance();

             Assert.Equal(-1, nextUnpurchasedInstance);
         }


         [Fact]
         public void ShouldUseCustomFormatterIfSetInDerivedToggle()
         {
             var mockGateway = new StoreGatewayMoqaLate();
             mockGateway.IsPurchasedSetReturnValue(true);

             var sut = new RepeatPurchaseWithNonDefualtFormatter()
             {
                 StoreGateway = mockGateway
             };

             var confuguredFormatter = sut.NameInstanceFormatter;

             Assert.IsType(typeof(RepeatPurchaseToggleNameInstanceFormatterMoqaLate), confuguredFormatter);
         }


         [Fact]
         public void ShouldErrorWhenNullUseCustomFormatterSetInDerivedToggle()
         {
             Assert.Throws<NullReferenceException>(() => { new RepeatPurchaseWithNullFormatter(); });
         }
    }
}