using InAppPurchaseToggle.Tests.ConcreteTestToggles;
using MoqaLate.Autogenerated;
using Xunit;

namespace InAppPurchaseToggle.Tests
{
    public class ToggleTests
    {
        [Fact]
        public void ShouldDefaultToRealWindowsStoreGateway()
        {
            var sut = new Feature1();

            Assert.IsType(typeof (RealStoreGateway), sut.StoreGateway);
        }


        [Fact]
        public void ShouldUseSpecifiedWindowsStoreGateway()
        {
            var mockGateway = new StoreGatewayMoqaLate();
            mockGateway.IsPurchasedSetReturnValue(true);

            var sut = new Feature1
                          {
                              StoreGateway = mockGateway
                          };

            var result = sut.IsPurchased;

            Assert.True(mockGateway.IsPurchasedWasCalledWith("Feature1"));
            Assert.True(result);
        }


        [Fact]
        public void ShouldMapName()
        {
            var mockNameMapper = new SingleToggleToStoreInAppOfferNameMapperMoqaLate();

            var sut = new Feature1
                          {
                              StoreGateway = new StoreGatewayMoqaLate(),
                              StoreInAppOfferNameMapper = mockNameMapper
                          };

            var dontCare = sut.IsPurchased;

            Assert.True(mockNameMapper.MapWasCalledWith(sut.GetType()));
        }
    }
}